version: '3.7'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - backend


  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_SSL: 'OFF'
    volumes:
      - ~/mysql_data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge


